### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by kopax** [ncd275/docx-extractor#1]
Hi, I wanted to retrieve meta from a docx document and I have found your module on npm,

After first call I have the following error:

```
  ● Test suite failed to run

    ReferenceError: primordials is not defined

      at fs.js:27:26
      at req_ (node_modules/natives/index.js:143:24)
      at Object.req [as require] (node_modules/natives/index.js:55:10)
      at Object.<anonymous> (node_modules/fstream/node_modules/graceful-fs/fs.js:1:64)
      at Object.<anonymous> (node_modules/fstream/node_modules/graceful-fs/graceful-fs.js:3:27)
```

- node: v12.10.0
- npm 6.11.3

**Comment by ndangles** [comment]
I don't see anything in my code or dependencies trying to reference something called `primordials`. is it possible this is a problem with something else in your project?

**Comment by kurucu** [comment]
It looks like its an issue with unzip?

https://github.com/mafintosh/prebuildify-ci/issues/5
